### ISSUE TITLE
Just a question on querying AD

### ISSUE THREAD

**Issue by commandline-be** [zorn96/ms_active_directory#43]
Hey

Looking for a way to query MS AD from any OS i ended up with ms_active_directory which does seem to be an impressive effort.

My intent is to query installed software, is this supported by this library ?

Also, is there commercial support available ?

**Comment by zorn96** [comment]
hi @commandline-be ! unfortunately, this library currently only supports reading/modifying things that are exposed over the LDAP protocol/Netlogon and DNS. installed software is not.

I might add some winrm (WS-Management protocol) or SMB support to this library in the future, and those would provide mechanisms for figuring out installed software. but the functionality to check installed software is part of windows server functionality, rather than active directory, so it's not exposed in the same way.

also I'm not exactly sure what you mean by commercial support, but we can talk about it. my current support model is "I try to ask people what they want from the library/for their issues" and I know that there's a number of companies using it, so when I have the time I try to make releases speedy. but I'm not myself a company so I don't offer support contracts if that's moreso what you're looking for
