### ISSUE TITLE
Address family not supported

### ISSUE THREAD

**Issue by romeoza** [zorn96/ms_active_directory#51]
Getting below error on RHEL8
Could be config issues. Any pointers??

Traceback (most recent call last):
  File "/tmp/6-11-localhost-dispatch-script.tmp.py", line 6, in <module>
    domain = ADDomain(example_domain_dns_name)
  File "/usr/local/lib/python3.6/site-packages/ms_active_directory/core/ad_domain.py", line 461, in __init__
    source_ip=self.source_ip)
  File "/usr/local/lib/python3.6/site-packages/ms_active_directory/environment/discovery/discovery_utils.py", line 105, in discover_kdc_domain_controllers_in_domain
    return _order_kdcs_by_rtt(all_kdc_records, server_limit, source_ip)
  File "/usr/local/lib/python3.6/site-packages/ms_active_directory/environment/discovery/discovery_utils.py", line 199, in _order_kdcs_by_rtt
    return _process_sort_return_rtt_ordering_results(lookup_rtt_fns, 'KDC', server_limit)
  File "/usr/local/lib/python3.6/site-packages/ms_active_directory/environment/discovery/discovery_utils.py", line 217, in _process_sort_return_rtt_ordering_results
    rtt_results.append(task.result())
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/ms_active_directory/environment/discovery/discovery_utils.py", line 299, in _check_kdc_availability_and_rtt
    test_socket6 = socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
  File "/usr/lib64/python3.6/socket.py", line 144, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol

**Comment by zorn96** [comment]
hi @romeoza ! could you provide some more detail on what your dns service records for your AD domain look like?

**Comment by eadelarosa** [comment]
- Hi, I have encountered this error just now. I'm running my code in AWS Lambda. 

**Environment:**

1. VPC: custom
2. Subnets: Private x 2
3. Security Groups: Private x 2 
4. Uses IPV4 CIDR only (i.e., No IPV6 CIDR associated)
5. AD Connector: Established to connect to on-prem active directory via AWS AD Connector (with both 389 and 636 ports open/allowed via SGs)

**1st & 2nd AWS Lambda Functions:**
- Has the proper roles and permission
- Associated with the custom VPC
- Associated with the private subnets and security groups where AD Connector is accessible

**Known:**
Two other Lambdas are on the same subnet and uses the same security groups. These Lambdas authenticate with the AD via the AWS AD Connector to access FSx File System Share using ```smbprotocol 1.10.0``` (from pypi.org) - all without issues. So I know the ports are working - via IPV4. 

**Third AWS Lambda Function - uses ```ms-active-directory module```**

Issue found based on the logs:
- It appears that when executing ```domain.create_session_as_user(user, password, authentication_mechanism=NTLM)```, the connection process is setting preference to using IPV6 which my VPC & subnet don't have (and we don't have any use for IPV6 after all - hence we don't configure it). The Lambda function times out completely - exhausting the full 15 min limit - because it wouldn't rotate to trying IPV4 connection after sometime.

**Question:**
- Is there a way for us to set the preference mode to using IPV4, instead of IPV6? The API documentation indicates that ```dns_nameservers``` can expect either IPV4 or IPV6. However, ```ldap_servers_or_uris``` seems to prefer only IPV6. Looking forward to your feedback. 


Portion of the ADDomain object dictionary after invoking ```ADDomain.(...)``` with parameters.

```

Server(host='AUZ-ADSVR-SUB-P01', port=389, use_ssl=False, allowed_referral_hosts=[('*', True)], tls=Tls(validate=<VerifyMode.CERT_NONE: 0>), get_info='SCHEMA', mode='IP_V6_PREFERRED')

```

Here's the full ADDomain object dictionary dump:

```

[INFO]	2023-01-12T08:55:50.073Z	840f9a94-004e-4a71-b74a-e895d323ce09	Value of ADDomain object: {'domain': 'abc.efg.org', 'site': 'sydney-opera-house-01', 'encrypt_connections': True, 'ca_certificates_file_path': None, 'ldap_servers': [Server(host='AUZ-ADSVR-SUB-P01', port=389, use_ssl=False, allowed_referral_hosts=[('*', True)], tls=Tls(validate=<VerifyMode.CERT_NONE: 0>), get_info='SCHEMA', mode='IP_V6_PREFERRED'), Server(host='AUZ-ADSVR-SUB-P02', port=389, use_ssl=False, allowed_referral_hosts=[('*', True)], tls=Tls(validate=<VerifyMode.CERT_NONE: 0>), get_info='SCHEMA', mode='IP_V6_PREFERRED'), Server(host='AUZ-ADSVR-SUB-P03', port=389, use_ssl=False, allowed_referral_hosts=[('*', True)], tls=Tls(validate=<VerifyMode.CERT_NONE: 0>), get_info='SCHEMA', mode='IP_V6_PREFERRED'), Server(host='AUZ-ADSVR-SUB-P04', port=389, use_ssl=False, allowed_referral_hosts=[('*', True)], tls=Tls(validate=<VerifyMode.CERT_NONE: 0>), get_info='SCHEMA', mode='IP_V6_PREFERRED'), Server(host='AUZ-ADSVR-SUB-P05', port=389, use_ssl=False, allowed_referral_hosts=[('*', True)], tls=Tls(validate=<VerifyMode.CERT_NONE: 0>), get_info='SCHEMA', mode='IP_V6_PREFERRED'), Server(host='AUZ-ADSVR-SUB-P06', port=389, use_ssl=False, allowed_referral_hosts=[('*', True)], tls=Tls(validate=<VerifyMode.CERT_NONE: 0>), get_info='SCHEMA', mode='IP_V6_PREFERRED')], 'ldap_uris': ['AUZ-ADSVR-SUB-P01', 'AUZ-ADSVR-SUB-P02', 'AUZ-ADSVR-SUB-P03', 'AUZ-ADSVR-SUB-P04', 'AUZ-ADSVR-SUB-P05', 'AUZ-ADSVR-SUB-P06'], 'kerberos_uris': [], 'dns_nameservers': ['172.7.9.10', '172.3.9.8'], 'source_ip': None, 'netbios_name': None, 'auto_configure_kerberos_client': False, '_sid': None}

```

And here's the error I received after executing ```domain.create_session_as_user(username, password, authentication_mechanism=NTLM)```

```

[ERROR]	2023-01-12T08:54:30.121Z	840f9a94-004e-4a71-b74a-e895d323ce09	Error was encountered while getting AD user session: err=OSError(97, 'Address family not supported by protocol'), <class 'OSError'>

```


Thanks in advance.
Regards,
Ed

**Comment by tobmat** [comment]
I'm getting the same error after completing the following steps from python prompt:
from ms_active_directory import ADDomain
domain = ADDomain('ourdomain.com')

>>> domain = ADDomain('ourdomain.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/ms_active_directory/core/ad_domain.py", line 461, in __init__
    source_ip=self.source_ip)
  File "/usr/local/lib/python3.6/site-packages/ms_active_directory/environment/discovery/discovery_utils.py", line 105, in discover_kdc_domain_controllers_in_domain
    return _order_kdcs_by_rtt(all_kdc_records, server_limit, source_ip)
  File "/usr/local/lib/python3.6/site-packages/ms_active_directory/environment/discovery/discovery_utils.py", line 199, in _order_kdcs_by_rtt
    return _process_sort_return_rtt_ordering_results(lookup_rtt_fns, 'KDC', server_limit)
  File "/usr/local/lib/python3.6/site-packages/ms_active_directory/environment/discovery/discovery_utils.py", line 217, in _process_sort_return_rtt_ordering_results
    rtt_results.append(task.result())
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/ms_active_directory/environment/discovery/discovery_utils.py", line 299, in _check_kdc_availability_and_rtt
    test_socket6 = socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
  File "/usr/lib64/python3.6/socket.py", line 144, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol

Note: Same logic is working from my local workstation WSL2 (Ubuntu) but failing from Centos 7 server.

**Comment by buedidoedi** [comment]
Had the same problem on RHEL8. The issue is that ipv6 stack is disabled on this machine.
`cat /sys/module/ipv6/parameters/disable` returns `1`

From my point of view the issue is located in:
`environment/discovery/discovery_utils.py`

trying to open a socket an a not existing network stack throws an exception.


```
test_socket4 = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
addr_tuple4 = (server_host, server_port)

test_socket6 = socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
addr_tuple6 = (server_host, server_port, 0, 0)

candidates.append((test_socket6, addr_tuple6))
candidates.append((test_socket4, addr_tuple4))

```

I guess a better approach would be to cat these exceptions:

```

    try:
        test_socket4 = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        addr_tuple4 = (server_host, server_port)
        candidates.append((test_socket4, addr_tuple4))
    except:
        logger.debug("ipv4 not available.\n") 
    try:
        test_socket6 = socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
        addr_tuple6 = (server_host, server_port, 0, 0)
        candidates.append((test_socket6, addr_tuple6))
    except:
        logger.debug("ipv6 not available.\n") 
 
```

**Comment by zorn96** [comment]
thanks all for the detailed information!
I was rolling with the ldap3 defaults for ipv6-preferred behavior, but didn't realize it could cause this issue. I'll try to put out a change in a bit to support piping through ipv4/ipv6 preferences when configuring a domain.

**Comment by romeoza** [comment]
@zorn96 any fix?
Thanks

**Comment by tobmat** [comment]
Any update on a fix or work-around for this @zorn96?

**Comment by zorn96** [comment]
PR: https://github.com/zorn96/ms_active_directory/pull/64

sorry for the delays. I got super busy with volunteering and got neglectful of this library. but I'm back and my new years resolution is to be less of a deadbeat around maintenance

**Comment by zorn96** [comment]
will come out in the next release

**Comment by zorn96** [comment]
newest version with this functionality is available on pypi now https://pypi.org/project/ms-active-directory/1.13.0/
