### ISSUE TITLE
Failing to create user: "unwillingToPerform"

### ISSUE THREAD

**Issue by ajcollett** [zorn96/ms_active_directory#72]
Hello!

First off, thank you for this Lib. I am hoping to automate and simplify some of our AD processes with it!

On to the issue. 
I am trying to test creating a user; however, I keep getting the error: unwillingToPerform

It doesn't seem to matter what mechanism of user_auth I use, and how many parameters I give the create_user function, I still get this error. 

``` bash
Traceback (most recent call last):
  File "/home/<snip>", line 123, in <module>
    session.create_unmanaged_user(
  File "/home/<snip>/.local/lib/python3.11/site-packages/ms_active_directory/core/ad_session.py", line 424, in create_unmanaged_user
    self._create_object(user_dn, ldap_constants.OBJECT_CLASSES_FOR_USER, user_attributes,
  File "/home/<snip>/.local/lib/python3.11/site-packages/ms_active_directory/core/ad_session.py", line 267, in _create_object
    raise ObjectCreationException('An exception was encountered creating an object with distinguished name {} '
ms_active_directory.exceptions.ObjectCreationException: An exception was encountered creating an object with distinguished name CN=Frederick Flintstone,CN=Users,DC=example,DC=com and object classes ['top', 'person', 'organizationalPerson', 'user']. LDAP result: {'result': 53, 'description': 'unwillingToPerform', 'dn': '', 'message': '0000052D: SvcErr: DSID-031A124C, problem 5003 (WILL_NOT_PERFORM), data 0\n\x00', 'referrals': None, 'type': 'addResponse'}
```

Unfortunately, this test AD DC is not using ldaps, and I've seen reports that using unencrypted connections can cause this. 

However, the `adcli` tool works fine to create a user against the same DC (although it creates it disabled). 

So, do you have any idea what might be the issue? Do I need a test DC with ldaps enabled?
Or is something else wrong in my config that adcli has right?

**Comment by zorn96** [comment]
Hi! So there’s no way to set a password in AD over LDAP without using some kind of encrypted channel. AD won’t allow it, and this library currently is LDAP based. AD also has some nuances around what it means to change vs reset a password

adcli, from my recollection, uses a mixture of protocols, and actually uses kadmin for the purpose of setting passwords. So it avoids a lot of the limitations you run into with the LDAP protocol.

There’s other protocols that can be used too. SAMR/SMB can also be used.

Longer term i would like to integrate more of those other protocols into this library, because there’s other things like AD policy objects that can’t have their details read over LDAP. But they’re not there yet. A major inhibiting factor is how much the libraries that provide cryptographic/network primitive for those protocols differ from platform to platform. Even stuff like adcli isn’t usable/doesn’t have the same capabilities on all flavors of linux because of things like that

so for now if you want to leverage this library you’ll unfortunately need to add TLS to your domain. Hope that helps clarify!

**Comment by ajcollett** [comment]
Hello @zorn96 , thanks, that is a really helpful response, and good info for me!

Yeah, adcli is pretty restrictive, I tried it for some user tasks and the options are pretty limited. I can create a user, but not set a pass or anything, and they show up disabled in the DC. 

Honestly, this library is one of the only ways to interact with an AD DC locally that I've found, in a platform agnostic manner. 
I was hoping to use terraform, but that module seems to be getting no attention.

Thanks again, we can close this one as answered then! 
Perhaps I can submit a MR to add a note to the docs about encryption requirements for creating users?

**Comment by zorn96** [comment]
You can create users without encryption I believe - but you cannot configure passwords for them without encryption of the channel. the same applies to computer accountd\s

**Comment by ajcollett** [comment]
Ah I see, well for my use case, creating users without a password isnt going to work in the workflow I'm testing. 

Though, I assume the Lib doesn't support this anyway? I tried creating a user without a password, but I believe that just generates a random one first? It also didn't work. 

We've ended up enabling ldaps. It was a less painful process than I thought, that's to a GitHub gist and OpenSSL!
